
POST http://localhost:5000/signup
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

POST http://localhost:5000/login
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

GET http://localhost:5000/dashboard
###

GET http://localhost:5000/
###
